### ISSUE TITLE
Project does not work with the master branch of open62541

### ISSUE THREAD

**Issue by harun27** [open62541pp/open62541pp#26]
Hi, 

I just want to note that the project does not work currently with the master branch of the open62541 project. The error I got while making the project was:

```
error: ‘struct UA_ServerConfig’ has no member named ‘customHostname’
  174 |     auto& ref = getConfig()->customHostname;
      |                              ^~~~~~~~~~~~~~
```

`customHostname` isn't used anymore.

**Comment by lukasberbuer** [comment]
Hi @harun27,

thanks for spotting this - that's interesting. I couldn't track down the exact commit on open62541 to this change and especially why it was removed.
It's still on the `1.3` branch: https://github.com/open62541/open62541/blob/1.3/include/open62541/server.h#L152

Similar issue @ open62541: https://github.com/open62541/open62541/issues/5132

Right now, I would prefer to wait until the next feature release (`v1.4.0`) and implement the changes here.
Do you need a solution urgently? What's your reason for using the current master instead of `v1.3.6`?

**Comment by harun27** [comment]
Hi @lukasberbuer,

thanks for asking. I just had the newest version already installed and wanted to try out your wrapper. So I got the error while trying, but I don't actually need the newest version, so I will just use the commit your submodule was on.
